### PR TITLE
Upgrade isort 4.3.0

### PR DESCRIPTION
**Pull request by bagerard**
Upgrade package to support 4.3.0

### CODE REVIEW

**Comment by asottile** [comment]
this'll happen automatically as part of a cron from https://github.com/pre-commit/cron-mirror-creation (once a week)

I'll kick the cron manually :)

**Comment by bagerard** [comment]
Wow, that's cool I didn't know it was possible to automate this kind of stuff. Thanks but otherwise I can also live with it for a week :)

**Comment by asottile** [comment]
@bagerard should be good to go with 4.3.0 and 4.3.1: https://travis-ci.org/pre-commit/cron-mirror-creation/jobs/333929126#L502

🎉

**Comment by asottile** [comment]
If you're curious, here's the code which auto-updates this: https://github.com/pre-commit/cron-mirror-creation

**Comment by bagerard** [comment]
sure, I'll have a look. Thanks!

**Pull request closed without merging**
